### ISSUE TITLE
QR code is not centered

### ISSUE THREAD

**Issue by thasmo** [neocotic/qr.js#30] opened 2015-03-29 15:44 UTC
I'm using qr.js within a polymer element and this happens:
![canvas](https://cloud.githubusercontent.com/assets/184284/6886364/3c752658-d63b-11e4-9ab0-117705201a8a.png)

I've inverted the colors to see the problem better on white background.

**Comment by neocotic** [comment] 2015-04-05 16:35
Closing this issue as it is a duplicate of #2.

Open to pull requests for this issue as I'd love to see it fixed but struggling to find the time right now.

**Closed by neocotic** 2015-04-05 16:35 UTC
